name: fastbraces
favicon: null
layout_spectrum: 0.47609
typography_spectrum: 0.5485015439335257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#251716'
    - '#f1cfbb'
    - '#808080'
    - '#ff0000'
  brandStrength: 0.125
  lightness: 0.513932267203927
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
