name: fastbraces
favicon: null
layout_spectrum: 0.45061632501892745
typography_spectrum: 0.5485015439335257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcf8f5'
    - '#25190b'
    - '#ff0000'
    - '#808000'
    - '#ffff00'
  brandStrength: 0.44251404399983585
  lightness: 0.513932267203927
  saturation: 0.302622533403337
  rhythmicContrast: 0.24124410026706755
purpose: []
