name: fastbraces
favicon: null
layout_spectrum: 0.70919
typography_spectrum: 0.5485015439335257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ecccc7'
    - '#ffffff'
    - '#8d8a98'
    - '#532016'
  brandStrength: 0.44251404399983585
  lightness: 0.513932267203927
  saturation: 0.302622533403337
  rhythmicContrast: 0.24124410026706755
purpose: []
